// Code generated by protoc-gen-go.
// source: kvs.proto
// DO NOT EDIT!

/*
Package kvs is a generated protocol buffer package.

It is generated from these files:
	kvs.proto

It has these top-level messages:
	StoreRequest
	StoreResponse
	LoadRequest
	LoadResponse
*/
package kvs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *StoreRequest) Reset()                    { *m = StoreRequest{} }
func (m *StoreRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()               {}
func (*StoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StoreRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StoreResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *StoreResponse) Reset()                    { *m = StoreResponse{} }
func (m *StoreResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()               {}
func (*StoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StoreResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LoadRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *LoadRequest) Reset()                    { *m = LoadRequest{} }
func (m *LoadRequest) String() string            { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()               {}
func (*LoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LoadResponse struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *LoadResponse) Reset()                    { *m = LoadResponse{} }
func (m *LoadResponse) String() string            { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()               {}
func (*LoadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LoadResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*StoreRequest)(nil), "kvs.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "kvs.StoreResponse")
	proto.RegisterType((*LoadRequest)(nil), "kvs.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "kvs.LoadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KVS service

type KVSClient interface {
	StoreItem(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	LoadItem(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
}

type kVSClient struct {
	cc *grpc.ClientConn
}

func NewKVSClient(cc *grpc.ClientConn) KVSClient {
	return &kVSClient{cc}
}

func (c *kVSClient) StoreItem(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := grpc.Invoke(ctx, "/kvs.KVS/StoreItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVSClient) LoadItem(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := grpc.Invoke(ctx, "/kvs.KVS/LoadItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KVS service

type KVSServer interface {
	StoreItem(context.Context, *StoreRequest) (*StoreResponse, error)
	LoadItem(context.Context, *LoadRequest) (*LoadResponse, error)
}

func RegisterKVSServer(s *grpc.Server, srv KVSServer) {
	s.RegisterService(&_KVS_serviceDesc, srv)
}

func _KVS_StoreItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).StoreItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvs.KVS/StoreItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).StoreItem(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVS_LoadItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSServer).LoadItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvs.KVS/LoadItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSServer).LoadItem(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvs.KVS",
	HandlerType: (*KVSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreItem",
			Handler:    _KVS_StoreItem_Handler,
		},
		{
			MethodName: "LoadItem",
			Handler:    _KVS_LoadItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvs.proto",
}

func init() { proto.RegisterFile("kvs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2e, 0x2b, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2e, 0x2b, 0x56, 0x32, 0xe3, 0xe2, 0x09, 0x2e,
	0xc9, 0x2f, 0x4a, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x4e,
	0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12,
	0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10, 0x8e, 0x92, 0x26, 0x17, 0x2f, 0x54, 0x5f, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x71, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31,
	0x58, 0x33, 0x47, 0x10, 0x8c, 0xab, 0x24, 0xcf, 0xc5, 0xed, 0x93, 0x9f, 0x98, 0x82, 0xd3, 0x06,
	0x90, 0x1b, 0x20, 0x0a, 0xa0, 0x46, 0x11, 0xe9, 0x06, 0xa3, 0x3c, 0x2e, 0x66, 0xef, 0xb0, 0x60,
	0x21, 0x13, 0x2e, 0x4e, 0xb0, 0x53, 0x3c, 0x4b, 0x52, 0x73, 0x85, 0x04, 0xf5, 0x40, 0x1e, 0x44,
	0xf6, 0x92, 0x94, 0x10, 0xb2, 0x10, 0xc4, 0x0a, 0x25, 0x06, 0x21, 0x43, 0x2e, 0x0e, 0x90, 0xa5,
	0x60, 0x4d, 0x02, 0x60, 0x15, 0x48, 0x8e, 0x94, 0x12, 0x44, 0x12, 0x81, 0x69, 0x49, 0x62, 0x03,
	0x87, 0x9b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x06, 0x52, 0x38, 0x44, 0x01, 0x00, 0x00,
}
